version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
    networks:
      - backend   

  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atp
    ports:
      - "3306:3306"
    networks:
      - backend   

networks:
   backend:
     driver: "bridge"